name: Go

on:
  workflow_call:
  push:
    branches:
    - "main"
    - "gh-readonly-queue/**/*"
  pull_request:
    branches: "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        ./scripts/cibuild
    
    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: maiao
        path: |
          dist
